[workspace]
authors = ["Guilherme Leobas <guilhermeleobas@gmail.com>"]
channels = ["conda-forge", "numba/label/dev"]
name = "numba"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[target.osx.activation.env]
NUMBA_DISABLE_OPENMP="1"

[dependencies]
python = "3.12.*"
llvmlite = "0.46.0.*"
pdbpp = ">=0.11.7,<0.12"
flake8 = ">=7.3.0,<8"
numpy = ">=2.3.3,<3"
cffi = ">=2.0.0,<3"
setuptools = ">=80.9.0,<81"
